version: 3

tasks:
  init:
    desc: initialise local environment
    silent: true
    cmds:
      - task: pre-commit:init
      - task: todo

  pre-commit:init:
    desc: initialises pre-commit hooks
    silent: true
    cmds:
      - pre-commit install &>/dev/null &

  todo:
    desc: show to do list to
    silent: true
    cmds:
      - cat ./.todo

  pubsub:start:
    desc: show to do list to
    silent: true
    cmds:
      - cmd: fuser -k 8085/tcp
        ignore_error: true
      - gcloud beta emulators pubsub start --project delineateio --host-port localhost:8085 &>/dev/null &
      - python dev/services/setup.py

  services:up:
    desc: starts all the services locally
    silent: true
    cmds:
      - cd $(pwd)/dev/services/add_account; functions_framework --target=main --port=8080 &>/dev/null &
      - cd -
      - cd $(pwd)/dev/services/add_email_address; functions_framework --target=subscribe --signature-type=event --port=8081 &>/dev/null &
      - echo "All services are up!"

  services:down:
    desc: stops all the services locally
    silent: true
    cmds:
      - cmd: fuser -k 8080/tcp
        ignore_error: true
      - cmd: fuser -k 8081/tcp
        ignore_error: true
      - echo "All services are down!"
